### ISSUE TITLE
Pagamento Transparente

### ISSUE THREAD

**Issue by JoaoPedroXD** [pagseguro/pagseguro-sdk-java#26]
Prezados,

Estou com um problema já tem dias e não consigo resolver, meu site está funcionando perfeitamente em minha máquina no servidor local, faço tudo pelo pagseguro-java-sdk, porém quando mando para o servidor web e tento criar uma nova sessão acontece isso:

`HTTP Status 500 - Servlet execution threw an exception

type Exception report

message Servlet execution threw an exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

java.lang.NoClassDefFoundError: Could not initialize class br.com.uol.pagseguro.api.http.JSEHttpClient
	com.uaocorporation.uaonome.Classes.sessao.processRequest(sessao.java:48)
	com.uaocorporation.uaonome.Classes.sessao.doGet(sessao.java:77)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.14 (Debian) logs.

Apache Tomcat/8.0.14 (Debian)`

o link para meu site é esse: http://nome.uaocorporation.com.br/nome.uaocorporation.com.br/sessao.
estou sem conseguir prosseguir com meu trabalho por conta disso, ficarei muito grato à quem conseguir resolver o me problema.

Atenciosamente,
João Pedro Nunes Queiroz.

**Comment by mam17** [comment]
Estou com o mesmo problema !

HTTP Status 500 - Could not initialize class br.com.uol.pagseguro.api.http.JSEHttpClient
type Exception report

message Could not initialize class br.com.uol.pagseguro.api.http.JSEHttpClient

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Could not initialize class br.com.uol.pagseguro.api.http.JSEHttpClient
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)

**Comment by mam17** [comment]
Problema resolvido!

Para resolver basta ao utilizar 
>
PagSeguro pag = PagSeguro.instance(new CommonsLoggerFactory(), new JSEHttpClient(), credential, environment);
ao invés de 
>
PagSeguro pag = PagSeguro.instance(credential, environment);
Logo depois adicione as seguintes dependencias no maven:

<dependency>
    <groupId>log4j</groupId>
    <artifactId>log4j</artifactId>
    <version>1.2.17</version>
</dependency>
<dependency>
    <groupId>commons-logging</groupId>
    <artifactId>commons-logging</artifactId>
    <version>1.2</version>
</dependency>

Pronto! Problema resolvido =D
